export const fifaTeamsSource = {
  sourceName: 'FIFA World Cup 2026 teams and group stage',
  sourceUrl: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/teams',
  verificationStatus: 'official',
  lastVerifiedAt: new Date('2026-05-15T00:00:00.000Z'),
};

export const flagCodes = {
  ALG: 'dz',
  ARG: 'ar',
  AUS: 'au',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BRA: 'br',
  CAN: 'ca',
  CIV: 'ci',
  COD: 'cd',
  COL: 'co',
  CPV: 'cv',
  CRO: 'hr',
  CUW: 'cw',
  CZE: 'cz',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  FRA: 'fr',
  GER: 'de',
  GHA: 'gh',
  HAI: 'ht',
  IRN: 'ir',
  IRQ: 'iq',
  JOR: 'jo',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  MAR: 'ma',
  MEX: 'mx',
  NED: 'nl',
  NOR: 'no',
  NZL: 'nz',
  PAN: 'pa',
  PAR: 'py',
  POR: 'pt',
  QAT: 'qa',
  RSA: 'za',
  SCO: 'gb-sct',
  SEN: 'sn',
  SUI: 'ch',
  SWE: 'se',
  TUN: 'tn',
  TUR: 'tr',
  URU: 'uy',
  USA: 'us',
  UZB: 'uz',
};

export const teams2026 = [
  { name: 'Mexico', nameTR: 'Meksika', nameEN: 'Mexico', fifaCode: 'MEX', confederation: 'CONCACAF', worldRanking: 15, group: 'A', flagEmoji: '🇲🇽', coachName: 'Javier Aguirre' },
  { name: 'South Africa', nameTR: 'Güney Afrika', nameEN: 'South Africa', fifaCode: 'RSA', confederation: 'CAF', worldRanking: 60, group: 'A', flagEmoji: '🇿🇦', coachName: 'Hugo Broos' },
  { name: 'Korea Republic', nameTR: 'Güney Kore', nameEN: 'Korea Republic', fifaCode: 'KOR', confederation: 'AFC', worldRanking: 25, group: 'A', flagEmoji: '🇰🇷', coachName: 'Hong Myung-bo' },
  { name: 'Czechia', nameTR: 'Çekya', nameEN: 'Czechia', fifaCode: 'CZE', confederation: 'UEFA', worldRanking: 41, group: 'A', flagEmoji: '🇨🇿', coachName: 'Ivan Hašek' },
  { name: 'Canada', nameTR: 'Kanada', nameEN: 'Canada', fifaCode: 'CAN', confederation: 'CONCACAF', worldRanking: 30, group: 'B', flagEmoji: '🇨🇦', coachName: 'Jesse Marsch' },
  { name: 'Switzerland', nameTR: 'İsviçre', nameEN: 'Switzerland', fifaCode: 'SUI', confederation: 'UEFA', worldRanking: 19, group: 'B', flagEmoji: '🇨🇭', coachName: 'Murat Yakin' },
  { name: 'Qatar', nameTR: 'Katar', nameEN: 'Qatar', fifaCode: 'QAT', confederation: 'AFC', worldRanking: 55, group: 'B', flagEmoji: '🇶🇦', coachName: 'Julen Lopetegui' },
  { name: 'Bosnia and Herzegovina', nameTR: 'Bosna-Hersek', nameEN: 'Bosnia and Herzegovina', fifaCode: 'BIH', confederation: 'UEFA', worldRanking: 65, group: 'B', flagEmoji: '🇧🇦', coachName: 'Sergej Barbarez' },
  { name: 'Brazil', nameTR: 'Brezilya', nameEN: 'Brazil', fifaCode: 'BRA', confederation: 'CONMEBOL', worldRanking: 6, group: 'C', flagEmoji: '🇧🇷', coachName: 'Carlo Ancelotti' },
  { name: 'Morocco', nameTR: 'Fas', nameEN: 'Morocco', fifaCode: 'MAR', confederation: 'CAF', worldRanking: 8, group: 'C', flagEmoji: '🇲🇦', coachName: 'Walid Regragui' },
  { name: 'Haiti', nameTR: 'Haiti', nameEN: 'Haiti', fifaCode: 'HAI', confederation: 'CONCACAF', worldRanking: 83, group: 'C', flagEmoji: '🇭🇹', coachName: 'Sébastien Migné' },
  { name: 'Scotland', nameTR: 'İskoçya', nameEN: 'Scotland', fifaCode: 'SCO', confederation: 'UEFA', worldRanking: 43, group: 'C', flagEmoji: '🏴', coachName: 'Steve Clarke' },
  { name: 'United States', nameTR: 'ABD', nameEN: 'United States', fifaCode: 'USA', confederation: 'CONCACAF', worldRanking: 16, group: 'D', flagEmoji: '🇺🇸', coachName: 'Mauricio Pochettino' },
  { name: 'Paraguay', nameTR: 'Paraguay', nameEN: 'Paraguay', fifaCode: 'PAR', confederation: 'CONMEBOL', worldRanking: 40, group: 'D', flagEmoji: '🇵🇾', coachName: 'Gustavo Alfaro' },
  { name: 'Australia', nameTR: 'Avustralya', nameEN: 'Australia', fifaCode: 'AUS', confederation: 'AFC', worldRanking: 27, group: 'D', flagEmoji: '🇦🇺', coachName: 'Tony Popovic' },
  { name: 'Türkiye', nameTR: 'Türkiye', nameEN: 'Türkiye', fifaCode: 'TUR', confederation: 'UEFA', worldRanking: 22, group: 'D', flagEmoji: '🇹🇷', coachName: 'Vincenzo Montella' },
  { name: 'Germany', nameTR: 'Almanya', nameEN: 'Germany', fifaCode: 'GER', confederation: 'UEFA', worldRanking: 10, group: 'E', flagEmoji: '🇩🇪', coachName: 'Julian Nagelsmann' },
  { name: 'Curaçao', nameTR: 'Curaçao', nameEN: 'Curaçao', fifaCode: 'CUW', confederation: 'CONCACAF', worldRanking: 82, group: 'E', flagEmoji: '🇨🇼', coachName: 'Dick Advocaat' },
  { name: "Côte d'Ivoire", nameTR: 'Fildişi Sahili', nameEN: "Côte d'Ivoire", fifaCode: 'CIV', confederation: 'CAF', worldRanking: 34, group: 'E', flagEmoji: '🇨🇮', coachName: 'Emerse Faé' },
  { name: 'Ecuador', nameTR: 'Ekvador', nameEN: 'Ecuador', fifaCode: 'ECU', confederation: 'CONMEBOL', worldRanking: 23, group: 'E', flagEmoji: '🇪🇨', coachName: 'Sebastián Beccacece' },
  { name: 'Netherlands', nameTR: 'Hollanda', nameEN: 'Netherlands', fifaCode: 'NED', confederation: 'UEFA', worldRanking: 7, group: 'F', flagEmoji: '🇳🇱', coachName: 'Ronald Koeman' },
  { name: 'Japan', nameTR: 'Japonya', nameEN: 'Japan', fifaCode: 'JPN', confederation: 'AFC', worldRanking: 18, group: 'F', flagEmoji: '🇯🇵', coachName: 'Hajime Moriyasu' },
  { name: 'Tunisia', nameTR: 'Tunus', nameEN: 'Tunisia', fifaCode: 'TUN', confederation: 'CAF', worldRanking: 44, group: 'F', flagEmoji: '🇹🇳', coachName: 'Sami Trabelsi' },
  { name: 'Sweden', nameTR: 'İsveç', nameEN: 'Sweden', fifaCode: 'SWE', confederation: 'UEFA', worldRanking: 38, group: 'F', flagEmoji: '🇸🇪', coachName: 'Jon Dahl Tomasson' },
  { name: 'Belgium', nameTR: 'Belçika', nameEN: 'Belgium', fifaCode: 'BEL', confederation: 'UEFA', worldRanking: 9, group: 'G', flagEmoji: '🇧🇪', coachName: 'Rudi Garcia' },
  { name: 'Egypt', nameTR: 'Mısır', nameEN: 'Egypt', fifaCode: 'EGY', confederation: 'CAF', worldRanking: 29, group: 'G', flagEmoji: '🇪🇬', coachName: 'Hossam Hassan' },
  { name: 'IR Iran', nameTR: 'İran', nameEN: 'IR Iran', fifaCode: 'IRN', confederation: 'AFC', worldRanking: 21, group: 'G', flagEmoji: '🇮🇷', coachName: 'Amir Ghalenoei' },
  { name: 'New Zealand', nameTR: 'Yeni Zelanda', nameEN: 'New Zealand', fifaCode: 'NZL', confederation: 'OFC', worldRanking: 85, group: 'G', flagEmoji: '🇳🇿', coachName: 'Darren Bazeley' },
  { name: 'Spain', nameTR: 'İspanya', nameEN: 'Spain', fifaCode: 'ESP', confederation: 'UEFA', worldRanking: 2, group: 'H', flagEmoji: '🇪🇸', coachName: 'Luis de la Fuente' },
  { name: 'Cabo Verde', nameTR: 'Yeşil Burun Adaları', nameEN: 'Cabo Verde', fifaCode: 'CPV', confederation: 'CAF', worldRanking: 69, group: 'H', flagEmoji: '🇨🇻', coachName: 'Bubista' },
  { name: 'Saudi Arabia', nameTR: 'Suudi Arabistan', nameEN: 'Saudi Arabia', fifaCode: 'KSA', confederation: 'AFC', worldRanking: 61, group: 'H', flagEmoji: '🇸🇦', coachName: 'Hervé Renard' },
  { name: 'Uruguay', nameTR: 'Uruguay', nameEN: 'Uruguay', fifaCode: 'URU', confederation: 'CONMEBOL', worldRanking: 17, group: 'H', flagEmoji: '🇺🇾', coachName: 'Marcelo Bielsa' },
  { name: 'France', nameTR: 'Fransa', nameEN: 'France', fifaCode: 'FRA', confederation: 'UEFA', worldRanking: 1, group: 'I', flagEmoji: '🇫🇷', coachName: 'Didier Deschamps' },
  { name: 'Senegal', nameTR: 'Senegal', nameEN: 'Senegal', fifaCode: 'SEN', confederation: 'CAF', worldRanking: 20, group: 'I', flagEmoji: '🇸🇳', coachName: 'Pape Thiaw' },
  { name: 'Norway', nameTR: 'Norveç', nameEN: 'Norway', fifaCode: 'NOR', confederation: 'UEFA', worldRanking: 31, group: 'I', flagEmoji: '🇳🇴', coachName: 'Ståle Solbakken' },
  { name: 'Iraq', nameTR: 'Irak', nameEN: 'Iraq', fifaCode: 'IRQ', confederation: 'AFC', worldRanking: 58, group: 'I', flagEmoji: '🇮🇶', coachName: 'Graham Arnold' },
  { name: 'Argentina', nameTR: 'Arjantin', nameEN: 'Argentina', fifaCode: 'ARG', confederation: 'CONMEBOL', worldRanking: 3, group: 'J', flagEmoji: '🇦🇷', coachName: 'Lionel Scaloni' },
  { name: 'Algeria', nameTR: 'Cezayir', nameEN: 'Algeria', fifaCode: 'ALG', confederation: 'CAF', worldRanking: 28, group: 'J', flagEmoji: '🇩🇿', coachName: 'Vladimir Petković' },
  { name: 'Austria', nameTR: 'Avusturya', nameEN: 'Austria', fifaCode: 'AUT', confederation: 'UEFA', worldRanking: 24, group: 'J', flagEmoji: '🇦🇹', coachName: 'Ralf Rangnick' },
  { name: 'Jordan', nameTR: 'Ürdün', nameEN: 'Jordan', fifaCode: 'JOR', confederation: 'AFC', worldRanking: 63, group: 'J', flagEmoji: '🇯🇴', coachName: 'Jamal Sellami' },
  { name: 'Portugal', nameTR: 'Portekiz', nameEN: 'Portugal', fifaCode: 'POR', confederation: 'UEFA', worldRanking: 5, group: 'K', flagEmoji: '🇵🇹', coachName: 'Roberto Martínez' },
  { name: 'Uzbekistan', nameTR: 'Özbekistan', nameEN: 'Uzbekistan', fifaCode: 'UZB', confederation: 'AFC', worldRanking: 57, group: 'K', flagEmoji: '🇺🇿', coachName: 'Fabio Cannavaro' },
  { name: 'Colombia', nameTR: 'Kolombiya', nameEN: 'Colombia', fifaCode: 'COL', confederation: 'CONMEBOL', worldRanking: 13, group: 'K', flagEmoji: '🇨🇴', coachName: 'Néstor Lorenzo' },
  { name: 'Congo DR', nameTR: 'Kongo DC', nameEN: 'Congo DR', fifaCode: 'COD', confederation: 'CAF', worldRanking: 56, group: 'K', flagEmoji: '🇨🇩', coachName: 'Sébastien Desabre' },
  { name: 'England', nameTR: 'İngiltere', nameEN: 'England', fifaCode: 'ENG', confederation: 'UEFA', worldRanking: 4, group: 'L', flagEmoji: '🏴', coachName: 'Thomas Tuchel' },
  { name: 'Croatia', nameTR: 'Hırvatistan', nameEN: 'Croatia', fifaCode: 'CRO', confederation: 'UEFA', worldRanking: 11, group: 'L', flagEmoji: '🇭🇷', coachName: 'Zlatko Dalić' },
  { name: 'Ghana', nameTR: 'Gana', nameEN: 'Ghana', fifaCode: 'GHA', confederation: 'CAF', worldRanking: 74, group: 'L', flagEmoji: '🇬🇭', coachName: 'Otto Addo' },
  { name: 'Panama', nameTR: 'Panama', nameEN: 'Panama', fifaCode: 'PAN', confederation: 'CONCACAF', worldRanking: 33, group: 'L', flagEmoji: '🇵🇦', coachName: 'Thomas Christiansen' },
].map((team) => ({
  ...team,
  flagCode: flagCodes[team.fifaCode] || '',
  sourceMetadata: fifaTeamsSource,
}));
